export const transactionRemarkSeeds: string[] = [
  'Dinner',
  'Lunch',
  'Breakfast',
  'Supper',
  'Parking',
  'Laundry',
  'Groceries',
  'Toll Fee',
  'Petrol',
  'Maintenance',
  'Rental',
  'Loan',
  `Ali's Birthday`,
  `Abu's Wedding`,
];