name: Firebase - Deploy Cloud Functions
on:
  push:
    branches:
       - main
    paths:
     - 'functions/**'
jobs:
  build-function:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
       node-version: '14'
    - name: Install NPM packages
      working-directory: functions
      run:  npm install
    - name: Transpile Typescript to Javascript
      working-directory: functions
      run: npm run build
    # Deploying the functions to firebase
    - name:  Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
          args: deploy --only functions
      env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_CI_TOKEN }}